# Generated by Django 4.2.2 on 2023-06-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='last_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Modo_de_juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='nickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=10)),
                ('Sc0re', models.IntegerField()),
            ],
        ),
    ]
